### PR TITLE
TESTS: Cucumber tests for the login/sign up

### PR DESCRIPTION
**Pull request by mzen17**
## What does this PR do?: 
Add a front-end testing using cucumber.

## Testing
1. Run cucumber

## Checklist
- [x] Code follows the project's style guidelines
- [x] Self-review completed
- [x] Documentation updated if necessary
- [x] No new warnings introduced
- [x] Tests added or updated as needed

### CODE REVIEW

**Review by avinashreddymudireddy — COMMENTED** [review]
Gets the following error:

(base) avinash@wireless-nat-inside projectdirectory-selt_2024_team_009 % cucumber             
undefined method `ignored?' for an instance of Gem::Specification (NoMethodError)
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/specification.rb:2193:in `method_missing'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.23/lib/bundler/rubygems_ext.rb:273:in `reject'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.23/lib/bundler/rubygems_ext.rb:273:in `matching_specs'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/dependency.rb:305:in `to_specs'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/specification.rb:1094:in `map'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/specification.rb:1094:in `unresolved_specs'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/specification.rb:1072:in `find_in_unresolved'
<internal:/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:83:in `block in require'
<internal:/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:39:in `synchronize'
<internal:/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:39:in `require'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.23/lib/bundler/rubygems_ext.rb:298:in `<module:Gem>'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.23/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.23/lib/bundler.rb:10:in `require_relative'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.23/lib/bundler.rb:10:in `<top (required)>'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.23/lib/bundler/setup.rb:6:in `require_relative'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.23/lib/bundler/setup.rb:6:in `<top (required)>'
<internal:/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/avinash/Downloads/PhD/Fall2024/SELT/projectdirectory-selt_2024_team_009/config/boot.rb:3:in `<top (required)>'
/Users/avinash/Downloads/PhD/Fall2024/SELT/projectdirectory-selt_2024_team_009/config/application.rb:1:in `require_relative'
/Users/avinash/Downloads/PhD/Fall2024/SELT/projectdirectory-selt_2024_team_009/config/application.rb:1:in `<top (required)>'
/Users/avinash/Downloads/PhD/Fall2024/SELT/projectdirectory-selt_2024_team_009/config/environment.rb:2:in `require_relative'
/Users/avinash/Downloads/PhD/Fall2024/SELT/projectdirectory-selt_2024_team_009/config/environment.rb:2:in `<top (required)>'
<internal:/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cucumber-rails-3.0.1/lib/cucumber/rails.rb:12:in `<top (required)>'
<internal:/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:132:in `require'
<internal:/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:132:in `rescue in require'
<internal:/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:126:in `require'
/Users/avinash/Downloads/PhD/Fall2024/SELT/projectdirectory-selt_2024_team_009/features/support/env.rb:7:in `<top (required)>'
<internal:/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cucumber-9.2.0/lib/cucumber/glue/registry_and_more.rb:124:in `load_code_file'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cucumber-9.2.0/lib/cucumber/runtime/support_code.rb:145:in `load_file'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cucumber-9.2.0/lib/cucumber/runtime/support_code.rb:82:in `block in load_files!'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cucumber-9.2.0/lib/cucumber/runtime/support_code.rb:81:in `each'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cucumber-9.2.0/lib/cucumber/runtime/support_code.rb:81:in `load_files!'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cucumber-9.2.0/lib/cucumber/runtime.rb:274:in `load_step_definitions'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cucumber-9.2.0/lib/cucumber/runtime.rb:74:in `run!'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cucumber-9.2.0/lib/cucumber/cli/main.rb:29:in `execute!'
/Users/avinash/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cucumber-9.2.0/bin/cucumber:9:in `<top (required)>'
/Users/avinash/.rbenv/versions/3.3.0/bin/cucumber:25:in `load'
/Users/avinash/.rbenv/versions/3.3.0/bin/cucumber:25:in `<main>'

**Comment by mzen17** [comment]
Interesting, that seems like a system bug. I'll test on a few more systems & get back the result.
If there are any other developers reading this PR, try to test it out as well.

**Comment by mzen17** [comment]
Interesting, I used a clean docker image with tag:ruby-3.3.0, ran bundle install, and then bundle exec cucumber, and it passed the tests.

image

I suspect that it might be an issue with other OS.

**Comment by avinashreddymudireddy** [comment]
it worked after I did `bundle exec rails app:update:bin`

**Review by avinashreddymudireddy — APPROVED** [review]
`rails db:drop db:create db:migrate`
`bundle exec rails app:update:bin` 
` bundle exec cucumber `
These commands worked

**Pull request merged**
